# Generated by Django 5.1.4 on 2024-12-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('number', models.CharField(max_length=10, verbose_name='num')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
